// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Nori - WWDC 2024",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Nori - WWDC 2024",
            targets: ["AppModule"],
            bundleIdentifier: "leejay.Nori---WWDC-2024",
            teamIdentifier: "2D93FKS52V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .twoPeople),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Unknown Usage Description")
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/maxxfrazer/FocusEntity", "1.1.1"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FocusEntity", package: "focusentity")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)